apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 5
  paused: true
  progressDeadlineSeconds: 600
  minReadySeconds: 0
  revisionHistoryLimit: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 20%
      maxSurge: 20%
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: nginx
        image: docker.io/mahonzhan/repo:leeroy-web
        resources:
          limits:
            cpu: 1
            memory: 512Mi
          requests:
            cpu: 0.5
            memory: 256Mi
        ports:
        - containerPort: 80
        startupProbe:
          httpGet:
            path: /index.html
            port: 80
          initialDelaySeconds: 0
          periodSeconds: 3
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 100
        livenessProbe:
          httpGet:
            path: /index.html
            port: 80
          initialDelaySeconds: 0
          periodSeconds: 3
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 2
        readinessProbe:
          httpGet:
            path: /index.html
            port: 80
          initialDelaySeconds: 0
          periodSeconds: 3
          timeoutSeconds: 1
          successThreshold: 3
          failureThreshold: 2
        securityContext:
          #runAsUser: 1000
          #runAsNonRoot: true
          #readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["all"]
            add: ["NET_BIND_SERVICE"]
